### ISSUE TITLE
division by zero

### ISSUE THREAD

**Issue by arve0** [mal/si-prefix#1]
Hi! I expected `siPrefix.byte.convert(0)` to yield `[0, 'B']`, but I get `[NaN, 'B']` because of division by zero here: https://github.com/mal/si-prefix/blob/master/src/unit.coffee#L18

Demo: https://runkit.com/embed/yrdq1xessxpz

**Comment by mal** [comment]
Sorry for the delay, I was on holiday 😁 

Thanks for the report, I've patched it and just released it in `0.2.0`!

**Comment by arve0** [comment]
No worries, thanks for the software and the fix 👍
